//! This library parses JSON generated by LDtk (Level Designers ToolKit) for use in Rust.
//! It is designed to be usable in any Rust program, including all game frameworks.
//!
//! Example:
//! ```
//! let file_path = "assets/AutoLayers_4_Advanced.ldtk".to_string();
//! let ldtk = LdtkFile::new(file_path);
//! println!("First level pixel height is {}!", ldtk.levels[0].px_hei);
//! ```
//!
//! See /examples directory for more.
//!

mod definitions;
pub mod ldtk_file;
mod levels;

pub use definitions::*;
pub use ldtk_file::LdtkFile;
pub use levels::*;
